# Generated by Django 4.1 on 2022-11-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
