# Generated by Django 4.1.1 on 2022-10-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='description',
        ),
    ]
