# Generated by Django 4.1.1 on 2022-11-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projectcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
