# Generated by Django 4.1 on 2023-03-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_feedback_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[('Excellent', 'Excellent'), ('Average', 'Average'), ('Poor', 'Poor')])),
            ],
        ),
    ]
