# Generated by Django 4.1.7 on 2023-02-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rateus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateus',
            name='rate',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50),
        ),
    ]
