# Generated by Django 4.1 on 2022-09-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoreValue',
            new_name='CoreValues',
        ),
    ]
