# Generated by Django 4.1 on 2023-02-16 14:13

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contract Awards [year]', help_text='At the [year] replace with the tendering year', max_length=255)),
                ('ref_number', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen')),
            ],
        ),
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_ID', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('job_description', models.TextField()),
                ('resposibilities', models.TextField()),
                ('qualification', models.TextField()),
                ('how_to_apply', models.TextField(blank=True)),
                ('advert_file', models.FileField(blank=True, upload_to='media')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Date Published')),
                ('deadline', models.DateField(blank=True, default=datetime.date.today, help_text='deadline for application')),
                ('job_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen')),
                ('job_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Attachment', 'Attachment')], default='Contract', help_text='Choose the appropriate job type to advertise', max_length=200)),
            ],
            options={
                'verbose_name': 'Job Advert',
            },
        ),
        migrations.CreateModel(
            name='PrequalifiedTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MSCSUA Pre-Qualified Suppliers [year]', help_text='At the [year] replace with the tendering year', max_length=255)),
                ('ref_number', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ref_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='media')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('tender_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen')),
            ],
            options={
                'verbose_name': 'Advertised Tender',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRegistrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Multi-National majority owned by Kenyan', 'Multi-National majority owned by Kenyan'), ('Multi-National Others', 'Multi-National Others')], max_length=512)),
                ('company_name', models.CharField(max_length=255)),
                ('KRA_pin', models.CharField(max_length=255)),
                ('company_email', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('physical_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('company_certificate_reg', models.FileField(upload_to='')),
                ('KRA_pin_certificate', models.FileField(upload_to='')),
                ('KRA_compliance_certificate', models.FileField(upload_to='')),
                ('company_memorandum_directors_page', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(to='career.service')),
            ],
        ),
    ]
