# Generated by Django 4.1.1 on 2022-10-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='supplierregistrationdetails',
            name='ownership',
            field=models.CharField(choices=[('Kenyan', 'Kenyan'), ('Multi-National majority owned by Kenyan', 'Multi-National majority owned by Kenyan'), ('Multi-National Others', 'Multi-National Others')], max_length=512),
        ),
    ]
