# Generated by Django 4.1.1 on 2022-11-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_service_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Advertised Tender'},
        ),
        migrations.AlterField(
            model_name='prequalifiedtender',
            name='title',
            field=models.CharField(default='MSCSUA Pre-Qualified Suppliers [year]', help_text='At the [year] replace with the tendering year', max_length=255),
        ),
    ]
