# Generated by Django 4.1.7 on 2023-02-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditServiceCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('receipt_issue', models.CharField(max_length=255)),
                ('complaint_log', models.CharField(max_length=255)),
                ('complaint_address', models.CharField(max_length=255)),
                ('satisfaction', models.BooleanField(blank=True, max_length=255)),
                ('license_payment_processing', models.CharField(blank=True, max_length=255)),
                ('automated_license_system', models.BooleanField(blank=True)),
                ('response', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('mode_of_response', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateField()),
                ('Quality', models.CharField(max_length=255)),
                ('integrity', models.CharField(max_length=255)),
                ('service_delivery', models.CharField(max_length=255)),
                ('problem_solving', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('mode_of_response', models.CharField(blank=True, max_length=200)),
                ('mode_of_response_type', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='change to published to be seen')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='PubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms of Service', max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='change to published to be seen')),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.pubcategory')),
            ],
            options={
                'verbose_name': 'Resource',
            },
        ),
    ]
