# Generated by Django 4.1.7 on 2023-02-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditservicecharter',
            name='automated_license_system',
            field=models.BooleanField(blank=True, help_text='Would it be convenient for you to have an automated Licensing system?'),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='comments',
            field=models.TextField(blank=True, help_text='Would you prefer receiving this questionnaire by email or other means?'),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='complaint_address',
            field=models.CharField(help_text='How long does it take for customer complaints to be addressed?', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='complaint_log',
            field=models.CharField(help_text='How do you log complaints', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='email',
            field=models.EmailField(blank=True, help_text='Your Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='license_payment_processing',
            field=models.CharField(blank=True, help_text='How long does it take to process a License after payment?', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='mode_of_response',
            field=models.CharField(blank=True, help_text='if Other Kindly specify', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='receipt_issue',
            field=models.CharField(help_text='How long does it take to be issued a cess receipt upon payment of cess or License', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='response',
            field=models.CharField(help_text='Other relevant comments or information:', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='satisfaction',
            field=models.BooleanField(blank=True, help_text='Are the complaints addressed to your satisfaction?', max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='Quality',
            field=models.CharField(help_text='Quality of our service', max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='comments',
            field=models.TextField(blank=True, help_text='Other relevant comments or Information'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='integrity',
            field=models.CharField(help_text='Courtesy/honesty/integrity', max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='mode_of_response',
            field=models.CharField(blank=True, help_text='Would you prefer receiving this questionnaire by email or other means?', max_length=200),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='mode_of_response_type',
            field=models.CharField(blank=True, help_text='If other Kindly specify', max_length=200),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='problem_solving',
            field=models.CharField(help_text='Addressing Issues/Problems', max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='response',
            field=models.CharField(help_text='Communication/Response', max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='service_delivery',
            field=models.CharField(help_text='Service Delivery time', max_length=255),
        ),
    ]
