# Generated by Django 4.1.1 on 2023-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_pubcategory_alter_publication_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditServiceCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
                ('receipt_issue', models.CharField(max_length=255)),
                ('complaint_log', models.CharField(max_length=255)),
                ('complaint_address', models.CharField(max_length=255)),
                ('satisfaction', models.CharField(max_length=255)),
                ('licence_payment_processing', models.CharField(max_length=255)),
                ('automated_licence_system', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
                ('Quality', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor')], max_length=255)),
                ('integrity', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor')], max_length=255)),
                ('service_delivery', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor')], max_length=255)),
                ('problem_solving', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor')], max_length=255)),
                ('response', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor')], max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
