# Generated by Django 4.1.1 on 2023-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auditservicecharter_customersurvey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditservicecharter',
            old_name='automated_licence_system',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='auditservicecharter',
            name='licence_payment_processing',
        ),
        migrations.RemoveField(
            model_name='auditservicecharter',
            name='organisation',
        ),
        migrations.AddField(
            model_name='auditservicecharter',
            name='automated_license_system',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditservicecharter',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='auditservicecharter',
            name='license_payment_processing',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditservicecharter',
            name='mode_of_response',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auditservicecharter',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='satisfaction',
            field=models.BooleanField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
