# Generated by Django 4.1.1 on 2023-02-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_rename_automated_licence_system_auditservicecharter_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditservicecharter',
            name='automated_license_system',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
