# Generated by Django 4.1.7 on 2023-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_auditservicecharter_automated_license_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersurvey',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='auditservicecharter',
            name='response',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='Quality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='integrity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='problem_solving',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='response',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='service_delivery',
            field=models.CharField(max_length=255),
        ),
    ]
