# Generated by Django 4.1.7 on 2023-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_rename_organisation_customersurvey_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='mode_of_response',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
