# Generated by Django 4.1.7 on 2023-02-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_customersurvey_mode_of_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='other',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
